### ISSUE TITLE
Keep geojson properties

### ISSUE THREAD

**Issue by kvalev** [mattijn/topojson#146] opened 2021-12-19 00:08 UTC
Hi, I noticed that all geojson feature properties are discarded when reading in the data. Is this intended?

**Comment by mattijn** [comment] 2021-12-19 12:57
Hm, I think it should be copied over, can you please provide a small reproducible example including the data?

**Comment by sheep-queen** [comment] 2022-01-26 21:24
Hello, I'm having this issue as well. Note that when I copy and paste the code for input data of type ["FeatureCollection or Features"](https://mattijn.github.io/topojson/example/input-types.html#featurecollection-or-features), the following is the JSON that is returned. Note that unlike the example response provided, this does not include the "properties": {"name": "abc"} attribute.
{
	"type": "Topology",
    	"objects": {
        	"data": {
            		"geometries": [
               			{"type": "Polygon", "arcs": [[-2, 0]]}, 
				{"type": "Polygon", "arcs": [[1, 2]]}
            		],
            		"type": "GeometryCollection"
		}
    	},
    	"bbox": [0.0, 0.0, 2.0, 1.0],
    	"arcs": [
        	[[1.0, 0.0], [0.0, 0.0], [0.0, 1.0], [1.0, 1.0]], [[1.0, 0.0], [1.0, 1.0]],
        	[[1.0, 1.0], [2.0, 1.0], [2.0, 0.0], [1.0, 0.0]]
    	]
}

**Comment by mattijn** [comment] 2022-01-28 10:44
Thanks for re-raising the issue @sheep-queen! Including an example. I can reproduce it with both shapely 1.7.1 and 1.8. Not sure what is going on.

**Comment by Dave-Evans** [comment] 2022-03-10 03:04
I noticed this as well. For what it's worth, I was able to keep the properties when converting to Topology from a GeoDataFrame.

**Comment by sheep-queen** [comment] 2022-03-18 00:05
> I noticed this as well. For what it's worth, I was able to keep the properties when converting to Topology from a GeoDataFrame.

Thanks @Dave-Evans! That works for me too - convert my shapefile to GeoDataFrame then run topology and output as TopoJSON.

**Comment by mattijn** [comment] 2022-04-07 19:05
Issue is fixed by #154

**Closed by mattijn** 2022-04-07 19:05 UTC
